// <auto-generated />
namespace CompetitionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FifthSad31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FifthSad31));
        
        string IMigrationMetadata.Id
        {
            get { return "202004090229208_FifthSad3.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
